from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.forms import ModelForm

class UserProfile(models.Model):
    '''
    Creates 1-to-1 relationship with Django User model
    for adding custom fields
    '''
    user = models.ForeignKey(User, unique = True)
    cn = models.CharField(max_length = 15, blank = True, null = True)
    all_mails = models.TextField(blank = True, null = True)
    secondary_password = models.CharField(max_length = 50, blank = True, null = True)

    class Meta:
        abstract = True

class GentooProfile(UserProfile):
    '''
    Extends the above UserProfile class with Gentoo-specific DB fields
    '''
    gentoo_status = models.CharField(max_length = 15)
    gentoo_access = models.TextField()
    gentoo_location = models.CharField(max_length = 50)
    gentoo_roles = models.CharField(max_length = 50)
    gpg_key = models.TextField(blank = True, null = True)
    gpg_fingerprint = models.TextField(blank = True, null = True)
    lat = models.CharField(max_length = 15, blank = True, null = True)
    lon = models.CharField(max_length = 15, blank = True, null = True)
    ssh_public_key = models.TextField(blank = True, null = True)
    gecos = models.CharField(max_length = 50)
    is_infra = models.BooleanField(default = False)
    is_devrel = models.BooleanField(default = False)
    is_recruiter = models.BooleanField(default = False)
    is_trustee = models.BooleanField(default = False)
    is_docs = models.BooleanField(default = False)
    is_security = models.BooleanField(default = False)
    is_pr = models.BooleanField(default = False)


def gentooExclude(priv):
    '''
    Helper function to generate a tuple with attributes that should
    be excluded from the edit form
    '''
    exclude = ['user', 'all_mails', 'gpg_key', 'gpg_fingerprint', 'ssh_public_key', 'gentoo_access']
    if not priv:
        for key in settings.LDAP_ACL_GROUPS.keys():
            exclude.append(key)
    return tuple(exclude)

'''
Below are the forms generated by the above models
'''

class UserProfileForm(ModelForm):
    '''
    UserProfile form
    '''
    class Meta:
        model = UserProfile
        exclude = ('user', 'all_mails')

class GentooProfileForm(ModelForm):
    '''
    GentooProfile form for unprivileged users
    Many fields are hidden
    '''
    class Meta:
        model = GentooProfile
        exclude = gentooExclude(False)

class GentooProfilePrivForm(ModelForm):
    '''
    GentooProfile form for privileged users
    All the fields are available
    '''
    class Meta:
        model = GentooProfile
        exclude = gentooExclude(True)
